### ISSUE TITLE
non-youtube links

### ISSUE THREAD

**Issue by PTL929** [chromix/redzone#1]
UI input for the standard links that will apply to each player.  These will be suppressed if they are left empty.  

Official Bio
Rivals Recruiting Profile
ESPN Stats
CBS Draft Profile
NFL.com Draft Profile
Rotoworld Updates
Wikipedia Page
Twitter Feed

Additionally - they should be "in-line" with what is currently done, and as I add other unique links to players, they should be able to appear together with no differences in spacing.

Separate ask - same vein:
To be used in the future (once player profiles are written by other sites - suppress this with a checked box like you did with the combine info because this will be a separate section):
External Draft Profiles:
NFL.com
CBS
Sports Illustrated
Yahoo
Fox
Walter Football

**Comment by chromix** [comment]
Aren't the CBS and NFL ones duplicated?

**Comment by PTL929** [comment]
No - cbs.sportsline and nfl.com are two separate sources.  Very different analysts (cbs = Pete Prisco/Dane Brugler/Rob Rang) v. (nfl.com = Mike Mayock/Daniel Jeremiah)

**Comment by chromix** [comment]
let me just say how crazy it is that you know the editors for those sites.

**Comment by PTL929** [comment]
Meh... maybe?  Probably tells you I shoulda made this website in college...

**Comment by chromix** [comment]
Fixed!

**Comment by PTL929** [comment]
Can you have the links that gets clicked on to open up a new tab, not create it in the existing tab
